#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl stop spice-resize-monitor.service || true
    systemctl disable spice-resize-monitor.service || true
fi

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'spice-resize-monitor.service' >/dev/null || true
fi
# End automatically added section


exit 0
