#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl stop spice-resize-monitor.service || true
    systemctl disable spice-resize-monitor.service || true
fi

#DEBHELPER#

exit 0
